<?php
/**
 * MagoArab PhoneMail Module
 *
 * @category  MagoArab
 * @package   MagoArab_PhoneMail
 * @author    MagoArab
 * @copyright Copyright (c) 2025
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="block block-forgot-password">
    <div class="block-title">
        <strong id="block-forgot-password-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Forgot Your Password?')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-forgot-password-heading">
        <form class="form password forget"
              action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('Please enter your phone number below to receive a password reset link.')) ?></div>
                <div class="field telephone required">
                    <label for="telephone" class="label"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                    <div class="control">
                        <input type="tel" 
                               name="telephone" 
                               alt="telephone" 
                               id="telephone" 
                               class="input-text" 
                               value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" 
                               data-validate="{required:true, 'validate-phone-number':true}" />
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
                </div>
                <div class="secondary">
                    <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "MagoArab_PhoneMail/js/forgot-password-form": {}
    }
}
</script>