<?php
/**
 * MagoArab PhoneMail Module - Existing account message template
 *
 * @category  MagoArab
 * @package   MagoArab_PhoneMail
 * @author    MagoArab
 * @copyright Copyright (c) 2025
 */
?>
<div class="message-error error message">
    <div>
        <?= $block->escapeHtml(__('We found an existing account with the phone number %1. If you already have an account, ', $block->getData('phone'))) ?>
        <a href="<?= $block->escapeUrl($block->getData('url')) ?>"><?= $block->escapeHtml(__('click here to sign in')) ?></a>.
    </div>
</div>